"""
Django settings for labourer_admin project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_USERNAME = os.environ.get('DEFAULT_USERNAME', 'ADMIN')
DEFAULT_PASSWORD = os.environ.get('DEFAULT_PASSWORD', 'Admin90')

SECRET_KEY = os.environ.get('django-insecure-4k%v0((t-#e%+f0%3k7gp9@#77z7e50dmh-1@b19!k*wc1(fx#')

DEBUG =  os.environ.get("DEBUG") == "True" 

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get('DEBUG', 'False') == 'False'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_COOKIE_DOMAIN = None  # Allow all domains
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False



LOGIN_URL = '/login/'  # Custom login page
LOGIN_REDIRECT_URL = '/dashboard/'  # Redirect to dashboard after login
LOGOUT_REDIRECT_URL = '/login/'  # Redirect to login after logout
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'labourers',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labourer_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
           
            ],
        },
    },
]

WSGI_APPLICATION = 'labourer_admin.wsgi.application'


# Database
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_TZ = True



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB - increased for image uploads
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'bmp', 'gif']
ALLOWED_DOCUMENT_EXTENSIONS = ['pdf', 'doc', 'docx', 'txt']
MAX_IMAGE_SIZE_MB = 10  # Maximum image file size in MB
MAX_DOCUMENT_SIZE_MB = 20  # Maximum document file size in MB


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# ==================== SECURITY SETTINGS ====================

# X-Frame-Options
X_FRAME_OPTIONS = 'SAMEORIGIN'

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://192.168.2.123:8000',
]

# ==================== SESSION SETTINGS ====================

SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_SAVE_EVERY_REQUEST = True

# ==================== LOGGING CONFIGURATION ====================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'image_upload_log': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'image_upload.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'labourers.upload': {
            'handlers': ['image_upload_log'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ==================== CUSTOM SETTINGS ====================


IMAGE_COMPRESSION_QUALITY = 85  # JPEG compression quality (1-100)
IMAGE_RESIZE_WIDTH = 800  # Default resize width for uploaded images
IMAGE_RESIZE_HEIGHT = 600  # Default resize height for uploaded images

# ID Scanning settings
ID_SCAN_MIN_CONFIDENCE = 0.7  # Minimum confidence for OCR text extraction
FACE_MATCH_MIN_CONFIDENCE = 0.8  # Minimum confidence for face matching
ID_IMAGE_MIN_WIDTH = 600  # Minimum width for ID images
ID_IMAGE_MIN_HEIGHT = 400  # Minimum height for ID images
PORTRAIT_IMAGE_MIN_WIDTH = 300  # Minimum width for portrait images
PORTRAIT_IMAGE_MIN_HEIGHT = 300  # Minimum height for portrait images

# Attendance settings
ATTENDANCE_GEOFENCE_RADIUS = 100  # Radius in meters for geofence
MAX_CHECKIN_DISTANCE_KM = 5  # Maximum distance from project location for check-in

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CREATE REQUIRED DIRECTORIES ====================

# Create required directories if they don't exist
required_dirs = [
    os.path.join(MEDIA_ROOT, 'portraits'),
    os.path.join(MEDIA_ROOT, 'id_documents'),
    os.path.join(MEDIA_ROOT, 'verification_scans'),
    os.path.join(MEDIA_ROOT, 'attendance'),
    os.path.join(MEDIA_ROOT, 'documents'),
    os.path.join(MEDIA_ROOT, 'contracts'),
    os.path.join(MEDIA_ROOT, 'signatures'),
    os.path.join(BASE_DIR, 'logs'),
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'temp_uploads'),
]

for dir_path in required_dirs:
    os.makedirs(dir_path, exist_ok=True)
    print(f"Created/Verified directory: {dir_path}")
   
