# Generated by Django 5.2.9 on 2025-12-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='location',
            field=models.CharField(default='Main Gate', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification_photos/'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labourer',
            name='portrait_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='labourer',
            name='portrait_image',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='labourer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labourers.labourer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='boundary_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='Store as: [[lat1,lng1], [lat2,lng2], ...]', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='entry_points',
            field=models.JSONField(blank=True, default=list, help_text='Store as: [[lat,lng], [lat,lng], ...]', null=True),
        ),
    ]
