# Generated by Django 5.2.9 on 2025-12-08 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourers', '0002_attendancelog_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourer',
            name='id_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='id_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='portrait_photo',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labourers', to='labourers.project'),
        ),
    ]
