# Generated by Django 5.2.9 on 2025-12-09 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourers', '0003_alter_labourer_id_back_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='contract',
            name='acknowledgment_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='acknowledgment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='audit_log',
            field=models.JSONField(default=list, help_text='Track all contract actions'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='generated_content',
            field=models.TextField(blank=True, help_text='Full contract with replaced tags'),
        ),
        migrations.AddField(
            model_name='contract',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='contracts/generated/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sent_to',
            field=models.CharField(blank=True, help_text='Email/Phone where sent', max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 signature data'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_device',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='auto_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='available_tags',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='default_delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('MANUAL', 'Manual')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='requires_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='template_file',
            field=models.FileField(blank=True, help_text='Upload Word/PDF template with dynamic tags', null=True, upload_to='contract_templates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'pdf', 'html'])]),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='template_type',
            field=models.CharField(choices=[('EMPLOYMENT', 'Employment Contract'), ('NDA', 'Non-Disclosure Agreement'), ('SAFETY', 'Safety Agreement'), ('TERMINATION', 'Termination Letter'), ('CUSTOM', 'Custom Document')], default='EMPLOYMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='minimum_experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='requires_background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='requires_certification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('SUPERVISOR', 'Supervisor'), ('FOREMAN', 'Foreman'), ('SKILLED', 'Skilled Worker'), ('SEMI_SKILLED', 'Semi-Skilled Worker'), ('UNSKILLED', 'Unskilled Worker'), ('OPERATOR', 'Machine Operator'), ('TECHNICIAN', 'Technician'), ('DRIVER', 'Driver'), ('SECURITY', 'Security Guard'), ('CLEANER', 'Cleaner'), ('CUSTOM', 'Custom Role')], default='CUSTOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='labourer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='labourers.labourer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sent_via',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('MANUAL', 'Manual')], default='EMAIL', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms_and_conditions',
            field=models.TextField(help_text='Auto-generated from template'),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='template_content',
            field=models.TextField(help_text='Use tags: {{full_name}}, {{serial_number}}, {{national_id}}, {{phone_number}}, {{email}}, {{designation}}, {{role}}, {{project}}, {{start_date}}, {{end_date}}, {{base_rate}}, {{contract_number}}, {{current_date}}'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='id_back_photo',
            field=models.ImageField(upload_to='id_documents/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='id_front_photo',
            field=models.ImageField(upload_to='id_documents/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='portrait_photo',
            field=models.ImageField(upload_to='portraits/'),
        ),
        migrations.AlterField(
            model_name='labourer',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique employee ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(default=dict, help_text="{'can_approve_timesheets': false, 'can_manage_equipment': false, 'can_create_tasks': false, 'can_view_reports': false, 'access_level': 1}"),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='labourers_c_contrac_e2e5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'created_at'], name='labourers_c_status_db54b4_idx'),
        ),
    ]
