# Generated by Django 5.2.9 on 2025-12-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourers', '0004_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='facial_match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='facial_recognition_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/checkin/'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='whitelist_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='within_geofence',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='within_operating_hours',
            field=models.BooleanField(default=True),
        ),
    ]
